name = "star-map-final"
account_id = "c5699cbcedce27a6ad755bdeb815f6de"
main = ".open-next/worker.js"
compatibility_date = "2025-12-29"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
workers_dev = false
preview_urls = false
routes = [
  { pattern = "starmapco.com/*", zone_name = "starmapco.com" },
  { pattern = "www.starmapco.com/*", zone_name = "starmapco.com" },
  { pattern = "starmapco.ca/*", zone_name = "starmapco.ca" },
  { pattern = "www.starmapco.ca/*", zone_name = "starmapco.ca" },
]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
NEXTJS_ENV = "production"
NEXT_INC_CACHE_R2_PREFIX = "incremental-cache"

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "star-map-final"

[[r2_buckets]]
binding = "NEXT_INC_CACHE_R2_BUCKET"
bucket_name = "cache"

[images]
binding = "IMAGES"
